name: Generate Android Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Generate keystore
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          keytool -genkeypair \
            -v \
            -storetype JKS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore ramrush-release.jks \
            -alias "$KEY_ALIAS" \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            -dname "CN=InfiniteMagazine228, OU=Dev, O=InfiniteMagazine, L=Hanoi, S=Hanoi, C=VN"

      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: ramrush-release-keystore
          path: ramrush-release.jks
